apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: finance-services-production
data:
  SPRING_PROFILES_ACTIVE: "production"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_SUHASAN_FINANCE: "INFO"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/accountdb"
  SPRING_DATASOURCE_USERNAME: "postgres"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  MANAGEMENT_SERVER_PORT: "9001"
