apiVersion: v1
kind: Secret
metadata:
  name: account-service-secrets
  namespace: finance-services-staging
type: Opaque
data:
  # These are placeholder values that will be replaced during deployment
  # DO NOT store actual secrets in this file - they should be generated during deployment
  POSTGRES_PASSWORD: <BASE64_DB_PASSWORD>
  REDIS_PASSWORD: <BASE64_REDIS_PASSWORD>
  JWT_SECRET: <BASE64_USER_JWT_SECRET>
  INTERNAL_JWT_SECRET: <BASE64_INTERNAL_JWT_SECRET>
