{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transaction-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "transaction-service.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
